[project]
name = "general"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=19.0.0",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
]
